.class public Lcom/apk/vn0;
.super Ljava/lang/Object;
.source "TagNodeAutoGeneratedCondition.java"

# interfaces
.implements Lcom/apk/tn0;


# static fields
.field public static final do:Lcom/apk/vn0;


# direct methods
.method public static constructor <clinit>()V
    .locals 1

    .line 1
    new-instance v0, Lcom/apk/vn0;

    invoke-direct {v0}, Lcom/apk/vn0;-><init>()V

    sput-object v0, Lcom/apk/vn0;->do:Lcom/apk/vn0;

    return-void
.end method

.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public do(Lcom/apk/kn0;)Z
    .locals 1

    .line 1
    iget-boolean v0, p1, Lcom/apk/kn0;->goto:Z

    if-eqz v0, :cond_0

    .line 2
    invoke-virtual {p1}, Lcom/apk/kn0;->while()Z

    move-result p1

    if-eqz p1, :cond_0

    const/4 p1, 0x1

    goto :goto_0

    :cond_0
    const/4 p1, 0x0

    :goto_0
    return p1
.end method

.method public toString()Ljava/lang/String;
    .locals 1

    const-string v0, "auto generated tagNode"

    return-object v0
.end method
