package com.apk;
/* compiled from: TagNodeAutoGeneratedCondition.java */
/* loaded from: classes7.dex */
public class vn0 implements tn0 {

    /* renamed from: do  reason: not valid java name */
    public static final vn0 f5181do = new vn0();

    @Override // com.apk.tn0
    /* renamed from: do */
    public boolean mo2609do(kn0 kn0Var) {
        return kn0Var.f2607goto && kn0Var.m1535while();
    }

    public String toString() {
        return "auto generated tagNode";
    }
}
